# -*- coding: utf-8 -*-
"""Aplicaciones a la física

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Yw6by311bJ7DOb2kapIq4BViOD8gfy8X

# Vectores aplicados a la física
"""

import math
class Vector:
  def __init__(self, coordenada_x, coordenada_y, coordenada_z):
    self.x = coordenada_x
    self.y = coordenada_y
    self.z = coordenada_z
    self.magnitud = (self.x**2 + self.y**2 + self.z**2)**0.5
  # Notación 
  def __str__(self) -> str:
    respuesta= "["+str(self.x)+" , "+str(self.y)+" , "+str(self.z)+"]"    
    return(respuesta) 
# Suma 
  def suma(self,otra):
    respuesta = Vector(self.x + otra.x, self.y + otra.y, self.z + otra.z)
    return(respuesta)
# Producto escalar 
  def escalar (self, otra):
    return(self.x* otra.x + self.y* otra.y + self.z*otra.z)
# Producto Vectorial 
  def vectorial (self, otra): 
    respuesta = Vector(self.y*otra.z-self.z*otra.y, self.z*otra.x-self.x*otra.z, self.x*otra.y-self.y*otra.x)
    return(respuesta)

"""# Uso de Objetos

## Sumatoria de Fuerzas
"""

# Defino vectores de fuerza 
print("Cálculo de la fuerza resultante", end="\n\n")
print("Digite el vector correspondiente a F_1")
x_1 = float(input("Ingrese la fuerza 1 en direeción X:"))
y_1 = float(input("Ingrese la fuerza 1 en direeción y:"))
z_1 = float(input("Ingrese la fuerza 1 en direeción z:"))

print("Digite el vector correspondiente a F_2")
x_2 = float(input("Ingrese la fuerza 2 en direeción X:"))
y_2 = float(input("Ingrese la fuerza 2 en direeción y:"))
z_2 = float(input("Ingrese la fuerza 2 en direeción z:"))

vec_1= Vector(x_1, y_1, z_1)
vec_2= Vector(x_2, y_2, z_2)

# Imprimo fuerzas y dirección de la fuerza resultante
print("Fuerza 1:", vec_1)
print("Fuerza 2:", vec_2, end="\n\n")
print("Suma de Fuerzas:", vec_1.suma(vec_2))
# Magnitud de la fuerza resultante 
vec_3= vec_1.suma(vec_2)
print("Magnitud de la fuerza resultante:",vec_3.magnitud)

"""## Torque"""

# Defino vectores 
print("Cálculo del torque", end="\n\n")

print("Digite vector posición")
x_1 = float(input("Ingrese la componente de la posición en X:"))
y_1 = float(input("Ingrese la componente de la posición en y:"))
z_1 = float(input("Ingrese la componente de la posición en z:"))


print("Digite vector Fuerza")
x_2 = float(input("Ingrese la fuerza en dirección X:"))
y_2= float(input("Ingrese la fuerza en dirección y:"))
z_2 = float(input("Ingrese la fuerza en dirección z:"))

vec_1= Vector(x_1, y_1, z_1) #radio vecotr
vec_2= Vector(x_2, y_2, z_2) #Fuerza

#imprime radio vector
print("Radio Vector:", vec_1)

#imprime vector fuerza
print("Fuerza:", vec_2, end="\n\n")

# Imprimo torque
print("Torque:", vec_1.vectorial(vec_2))